//-------------------------------------------------BenutzerEndpunkte---------------------------------------------------

### Login user
POST http://localhost:8080/einloggen
Content-Type:application/json

{
  "benutzerName": "moritzrose",
  "passwort": "moritzrose"
}

### Logout user
POST http://localhost:8080/ausloggen
Content-Type:application/json

### Register user
POST http://localhost:8080/registrieren
Content-Type:application/json

{
  "benutzerName":"tillhueser",
  "passwort1":"tillhueser",  "passwort2":"tillhueser",
  "vorname":"Till",
  "nachname":"Hüser",
  "geschlecht":"männlich"
}
###
//-------------------------------------------------StimmungenEndpunkte---------------------------------------------------
GET http://localhost:8080/stimmungen
Content-Type:application/json

###
POST http://localhost:8080/stimmung
Content-Type:application/json

{
  "rating":3,
  "kommentar":"Was für ein toller Tag"
}

###

//-------------------------------------------------KryptonitEndpunkte---------------------------------------------------
### Alle Kryptonite holen
GET http://localhost:8080/kryptonite
Content-Type:application/json

### Erstelle Kryptonit
POST http://localhost:8080//kryptonit
Content-Type:application/json

{
  "bezeichnung":"Nudeln"
}

### Lösche Kryptonit
DELETE http://localhost:8080/kryptonit/1
Content-Type:application/json


### Ändere Kryptonitbezeichnung
PUT http://localhost:8080/kryptonit/10
Content-Type:application/json

{
  "veraenderterName": "NichtZocken!"
}

### Füge neuen Kryptoniteintrag hinzu

POST http://localhost:8080//kryptonit/1/eintrag
Content-Type:application/json

{
  "haeufigkeit": 4
}

###
//-------------------------------------------------BalsamEndpunkte---------------------------------------------------

### Alle Balsame holen
GET http://localhost:8080/balsame
Content-Type:application/json

### Erstelle Balsam
POST http://localhost:8080//balsam
Content-Type:application/json

{
  "bezeichnung":"Freunde"
}

### Lösche Balsam
DELETE http://localhost:8080/balsam/1
Content-Type:application/json

### Erstelle Balsameintrag
POST http://localhost:8080//balsam/1/eintrag
Content-Type:application/json